cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='Home'),
    path('products', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

]

users/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from .views import display_products, display_orders,user_profile,user_logout , login_view , edit_product, delete_product


app_name = 'users' 

urlpatterns = [
   path('vendor/', login_view, name='login'),
   path('dashboard/', display_products, name='vendor'), 
   path('add/', views.add_product, name='add-products'),
   path('orders/', display_orders, name='orders'),
   path('edit-product/<int:product_id>/', edit_product, name='edit-product'),
   path('profile/', user_profile, name='profile'),
   path('logout/', user_logout, name='logout'),
   path('delete-product/<int:product_id>/', delete_product, name='delete-product'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Index
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    vendor = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    class Meta:
        ordering = ('name',)
        indexes = [
            Index(fields=['id', 'slug']),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
from .models import Category, Product

from django.views import generic

def index(request):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    context = {
        'products':products,
    }
    return render(request,'shop/index.html',context)    



def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    context = {'category': category, 'categories': categories, 'products': products}
    return render(request, 'shop/product/list.html', context)


# class ProductListView(generic.ListView):
#     template_name = 'shop/product/list.html'

#     def get_queryset(self):
#         return Product.objects.filter(available=True)

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         category = None
#         if category_slug:
#             category = get_object_or_404(Category, slug=category_slug)
#         context['category'] = category
#         context['categories'] = Category.objects.all()





def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {'product': product, 'cart_product_form': cart_product_form}
    return render(request, 'shop/product/detail.html', context)


# class ProductDetialView(generic.DetailView):

#     template_name = 'shop/product/detail.html'
#     model = Product
#     form_class = CartAddProductForm

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['products'] = get_object_or_404(Product, 
#         id=id, slug=slug, available=True)
#         return context

shop/templates/shop/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Omni{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <style>
        /* Floating Chatbot Icon Styles with Animation */
        .chatbot-icon {
            position: fixed;
            bottom: 20px;
            right: 20px;
            z-index: 1000;
            animation: moveUpDown 2s infinite alternate; /* Use the animation here */
        }
        
        .chatbot-icon a {
            display: block;
            background-color: #4CAF50;
            padding: 10px;
            border-radius: 50%;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
            transition: background-color 1.5s ease;
        }
        
        .chatbot-icon img {
            width: 50px;
            height: 50px;
        }
        
        /* Change color on hover */
        .chatbot-icon a:hover {
            background-color: #45a049;
        }
        
        /* Animation keyframes for moving up and down */
        @keyframes moveUpDown {
            0% {
                transform: translateY(0);
            }
            100% {
                transform: translateY(-20px);
            }
        }
        #kommunicate-widget-iframe{
            visibility:hidden;
        }
        .kommunicate-custom-iframe{
            display:none;
        }
        {% block style %}
        {% endblock %}
    </style>
    {% block head %}
    {% endblock %}

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static "fonts/icomoon/style.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery-ui.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "css/aos.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body>
    <div class="site-wrap">
        {% include 'shop/base/navbar.html' %}
        {% block content %}
        {% endblock %}
        {% include 'shop/base/footer.html' %}
    </div>
    <script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "js/jquery-ui.js" %}"></script>
    <script src="{% static "js/popper.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/owl.carousel.min.js" %}"></script>
    <script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
    <script src="{% static "js/aos.js" %}"></script>
    <script src="{% static "js/main.js" %}"></script>
    <script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
    <df-messenger
      intent="WELCOME"
      chat-title="OmniBot"
      agent-id="5ab7752d-a253-41b4-8503-2cbde0da44de"
      language-code="en"
    ></df-messenger>
    <script>
        {% block script %}
    
        {% endblock %}
    </script>
</body>
</html>

shop/templates/shop/base/footer.html
<footer class="site-footer border-top">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 mb-5 mb-lg-0">
                <div class="row">
                    <div class="col-md-12">
                        <h3 class="footer-heading mb-4">Navigations</h3>
                    </div>
                    <div class="col-md-6 col-lg-4">
                        <ul class="list-unstyled">
                            <li><a href="#">Sell online</a></li>
                            <li><a href="#">Features</a></li>
                            <li><a href="#">Shopping cart</a></li>
                            <li><a href="#">Store builder</a></li>
                        </ul>
                    </div>
                    
                </div>
            </div>
          
            <div class="col-md-6 col-lg-3">
                <div class="block-5 mb-5">
                    <h3 class="footer-heading mb-4">Contact Info</h3>
                    <ul class="list-unstyled">
                        <li class="address">Hyd,Banjarahills Road No 10</li>
                        <li class="phone"><a href="tel://23923929210">+91 79890 52767</a></li>
                        <li class="email">mdwaseel2311@gmail.com</li>
                    </ul>
                </div>
            </div>
            
        </div>
    </div>
</footer>

shop/templates/shop/base/navbar.html
    <header class="site-navbar" role="banner">
        <div class="site-navbar-top">
            <div class="container">
                <div class="row align-items-center">

                    <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
                        <form action="" class="site-block-top-search rounded-md border-2 border-purple-300">
                            <span class="icon icon-search2"></span>
                            <input type="text" class="form-control border-0" placeholder="Search">
                        </form>
                    </div>

                    <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
                        <div class="site-logo">
                            <a href="{% url 'shop:Home'%}" class="js-logo-clone">Omni-Mart</a>
                        </div>
                    </div>

                    <div class="col-6 col-md-4 order-3 order-md-3 text-right">
                        <div class="site-top-icons">
                            <ul>
                                <li><a href="{% url 'users:login' %}"><span class="icon icon-person"></span></a></li>
                                <li>
                                    <a href="{% url "cart:cart_detail" %}" class="site-cart">
                                        <span class="icon icon-shopping_cart"></span>
                                        <span class="count">
                                        {% with total_items=cart|length %}
                                            {% if cart|length > 0 %}
                                                {{ total_items|pluralize }}
                                            {% else %}
                                                0
                                            {% endif %}
                                        {% endwith %}
                                        </span>
                                    </a>
                                </li>
                                <li class="d-inline-block d-md-none ml-md-0"><a href="#"
                                        class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a></li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <nav class="site-navigation text-right text-md-center " style="background:rgb(88 28 135 ); "  role="navigation">
            <div class="container">
                <ul class="site-menu js-clone-nav d-none  d-md-block text-white" >
                    <li><a href="/" class="text-white " >Home</a></li>
                    <li><a href="{% url "shop:product_list" %}" class="text-white">Shop</a></li>
                    <li><a href="#" class="text-white">About</a></li>
                    <li><a href="#" class="text-white">Contact</a></li>
                    {% comment %} <li><a href="#" class="text-white">Virtual Chat-Bot</a></li> {% endcomment %}
                </ul>
            </div>
        </nav>
    </header>